from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(plain_password: str):

    '''

    Function to generate a hashed password.

    Examples generated by this function are stored in 'data-users.json'

    '''

    return pwd_context.hash(plain_password)
